#! /usr/bin/env php

<?php

use Acme\NewCommand;
use Symfony\Component\Console\Application;

require 'vendor/autoload.php';

$app = new Application('Own Installer Tool', 'version 1.0');

$app->add(new NewCommand(new GuzzleHttp\Client));

$app->run();
